#图片验证码的有效期,单位：秒
IMAGE_CODE_REDIS_EXPIRE=180
SMS_CODE_REDIS_EXPIRE=300
SEND_SMS_CODE_INTERVAL=60
LOGIN_ERROR_MAX_TIMES=3
LOGIN_ERROR_FORBID_TIME=600
QINIU_URL_DOMAIN="http://pt9tjwrjg.bkt.clouddn.com"
AREA_INFO_REDIS_CACHE_EXPIRES=86400